/* Companion robot */
#define DISPLAY_COLOR_ROBOT_SCREEN_BG      0x0D1420
#define DISPLAY_COLOR_ROBOT_HEAD_BG        0xB8C4D0
#define DISPLAY_COLOR_ROBOT_HEAD_BORDER    0x5A6B7A
#define DISPLAY_COLOR_ROBOT_BODY_BG        0x5A6B7A

#define DISPLAY_COLOR_ROBOT_EYES_NORMAL    0x4FD8E8
#define DISPLAY_COLOR_ROBOT_EYES_LOW       0xF0A830
#define DISPLAY_COLOR_ROBOT_EYES_CRITICAL  0xE84B4B

#define DISPLAY_COLOR_ROBOT_ANTENNA_USB    0x3B82F6
#define DISPLAY_COLOR_ROBOT_ANTENNA_BLE    0x7C6FF0
#define DISPLAY_COLOR_ROBOT_ANTENNA_OFF    0x8A94A0

#define DISPLAY_COLOR_ROBOT_TEXT           0xE8EDF2
#define DISPLAY_COLOR_ROBOT_TEXT_DIM       0xB8C4D0

#define DISPLAY_COLOR_ROBOT_MOD_ACTIVE     0xE8EDF2
#define DISPLAY_COLOR_ROBOT_MOD_INACTIVE   0x3A4552
#define DISPLAY_COLOR_ROBOT_CAPS_WORD      0xFFBF00
